version: "3.8"

services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    hostname: broker
    restart: unless-stopped
    ports:
      # host tools (kcat, kafkacat, kafka-console-producer on host) -> connect to localhost:29092
      - "29092:29092"
      # controller internal port (no need to expose to host usually)
      - "29093:29093"
    environment:
      # KRaft single-node config (quotes used where value contains @ or commas)
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker:29093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
    volumes:
      - broker-data:/var/lib/kafka/data
    networks:
      - saga-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: shubham
      POSTGRES_PASSWORD: myAdmin123
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shubham -d inventory"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - saga-network

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - saga-network

networks:
  saga-network:
    driver: bridge

volumes:
  pgdata:
  broker-data:
